/*
  Warnings:

  - You are about to drop the `Found` table. If the table is not empty, all the data it contains will be lost.
  - You are about to drop the `Lost` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropForeignKey
ALTER TABLE "Found" DROP CONSTRAINT "Found_userId_fkey";

-- DropForeignKey
ALTER TABLE "Lost" DROP CONSTRAINT "Lost_userId_fkey";

-- DropTable
DROP TABLE "Found";

-- DropTable
DROP TABLE "Lost";

-- CreateTable
CREATE TABLE "LostAndFound" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userId" INT4 NOT NULL,
    "name" STRING NOT NULL,
    "lastname" STRING NOT NULL,
    "phone" STRING NOT NULL,
    "email" STRING NOT NULL,
    "title" STRING NOT NULL,
    "city" STRING NOT NULL,
    "whereDidFind" STRING NOT NULL,
    "exatLocation" STRING NOT NULL,
    "airoport" STRING NOT NULL,
    "buss" STRING NOT NULL,
    "hotel" STRING NOT NULL,
    "InCity" STRING NOT NULL,
    "description" STRING NOT NULL,
    "findingDate" TIMESTAMP(3) NOT NULL,
    "mapAddress" STRING NOT NULL,
    "photo" STRING NOT NULL,
    "label" STRING NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "LostAndFound_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "LostAndFound" ADD CONSTRAINT "LostAndFound_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
