-- CreateTable
CREATE TABLE "User" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "lastname" STRING NOT NULL,
    "password" STRING NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Lost" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userId" INT4 NOT NULL,
    "name" STRING NOT NULL,
    "lastname" STRING NOT NULL,
    "phone" STRING NOT NULL,
    "email" STRING NOT NULL,
    "title" STRING NOT NULL,
    "city" STRING NOT NULL,
    "whereDidFind" STRING NOT NULL,
    "airoport" STRING NOT NULL,
    "buss" STRING NOT NULL,
    "hotel" STRING NOT NULL,
    "InCity" STRING NOT NULL,
    "description" STRING NOT NULL,
    "findingDate" TIMESTAMP(3) NOT NULL,
    "mapAddress" STRING NOT NULL,
    "photo" STRING NOT NULL,
    "label" STRING NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Lost_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Found" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userId" INT4 NOT NULL,
    "name" STRING NOT NULL,
    "lastname" STRING NOT NULL,
    "phone" STRING NOT NULL,
    "email" STRING NOT NULL,
    "title" STRING NOT NULL,
    "city" STRING NOT NULL,
    "whereDidFind" STRING NOT NULL,
    "airoport" STRING NOT NULL,
    "buss" STRING NOT NULL,
    "hotel" STRING NOT NULL,
    "InCity" STRING NOT NULL,
    "description" STRING NOT NULL,
    "findingDate" TIMESTAMP(3) NOT NULL,
    "mapAddress" STRING NOT NULL,
    "photo" STRING NOT NULL,
    "label" STRING NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Found_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Lost" ADD CONSTRAINT "Lost_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Found" ADD CONSTRAINT "Found_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
